null_blk: Fix compile error occuring when CONFIG_NVM is not set
drivers/block/null_blk.c:569:27: error: storage size of 'null_lnvm_dev_ops' isn't known

The forward declaration of 'null_lnvm_dev_ops' is used only for a function argument
that is never used but gcc 6.2 doesn't seem to care.